spring.application.name=minifarm


# --------------------------------------------
# Server
# --------------------------------------------
server.port=8080

# --------------------------------------------
# DataSource (PostgreSQL)
# --------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/minifarm
spring.datasource.username=minifarm
spring.datasource.password=minifarm

# --------------------------------------------
# JPA / Hibernate
# --------------------------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --------------------------------------------
# Flyway
# --------------------------------------------
spring.flyway.enabled=true

# --------------------------------------------
# (선택) JDK 21 Virtual Threads
# --------------------------------------------
spring.threads.virtual.enabled=true
